build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.3
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
    dependencies:
        override:
            - composer install --no-scripts

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: ["src/*", "tests/*"]
