build:
    nodes:
        analysis:
            environment:
                node: v10.13
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: ["src/*"]